INSERT INTO  TODO(ID,USERNAME ,DESCRIPTION ,TARGET_DATE ,DONE ) VALUES (10001,'KISHORE','Learn Freelancing',CURRENT_DATE(), false);
INSERT INTO  TODO(ID,USERNAME ,DESCRIPTION ,TARGET_DATE ,DONE ) VALUES (10002,'KISHORE','Learn Investing',CURRENT_DATE(), false);
INSERT INTO  TODO(ID,USERNAME ,DESCRIPTION ,TARGET_DATE ,DONE ) VALUES (10003,'KISHORE','Learn Cloud',CURRENT_DATE(), false);